[project]
name = "accept-school-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-telegram-bot>=21.10",
    "ruff>=0.9.4",
]

[tool.ruff]
extend-include = ["*.ipynb"]
fix=true
line-length = 90
